version: "2"

services:
   jekyll:
      build: .
      ports:
         - "14000:4000"
      environment:
         - REPOSITORY=https://github.com/crazycapivara/docker-jekyll.git
         - BRANCH=feature/blog
      command: jekyll serve -s /blog/blog -H 0.0.0.0

